# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User: plaintext

    providers:
        main:
            entity:
                class:    UserBundle\Entity\User
                property: username

    firewalls:
        main:
            anonymous: ~
            provider:  main
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   app_logout

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }