services:
    datafixtures.archive:
        class: Exercices\ArchiveBundle\DataFixtures\ORM\ArchiveFixtures
        tags: [doctrine.fixture.orm]

    archive.DownloadFileFromArchive:
        class: Exercices\ArchiveBundle\Services\DownloadFileFromArchive

  
#    exercices_archive.example:
#        class: Exercices\ArchiveBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


